In [1]:
import numpy as np
import torch

In [2]:
# number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
torch.tensor(4.).dtype

torch.float32

In [4]:
torch.tensor(4).dtype

torch.int64

In [5]:
# vector
t2 = torch.tensor([1. ,2 ,3, 4])
t2

tensor([1., 2., 3., 4.])

In [6]:
# Matrix
t3 = torch.tensor([[5., 6],
                  [7, 8],
                  [9, 9]])
t3

tensor([[5., 6.],
        [7., 8.],
        [9., 9.]])

In [7]:
# 3-dimensional array
t4 = torch.tensor([[[11, 12, 13],
                    [13, 14, 15]],
                   
                   [[15, 16, 17],
                    [17, 18, 19.]],
                    
                   [[20, 21, 22],
                    [22, 23, 24]],
                  
                   [[25, 26, 27],
                    [28, 29, 30]]])

t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]],

        [[20., 21., 22.],
         [22., 23., 24.]],

        [[25., 26., 27.],
         [28., 29., 30.]]])

In [8]:
t1.shape

torch.Size([])

In [9]:
t2.shape

torch.Size([4])

In [10]:
t4.shape

torch.Size([4, 2, 3])

#### Tensor operations and gradients

In [11]:
# Create tensors.
x = torch.tensor(3., requires_grad=True)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [12]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [13]:
# Compute derivatives
y.backward()

In [14]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: tensor(4.)
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [15]:
# From numpy array to torch tensor
u = np.array([[1, 2], [3, 4.]])
v = torch.from_numpy(u)
v

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [16]:
u.dtype, v.dtype

(dtype('float64'), torch.float64)

In [17]:
# From torch tensor to numpy array
v.numpy()

array([[1., 2.],
       [3., 4.]])